container:
    image: archlinux/base
    cpu: 8
    memory: 24G

task:
    script:
        - pacman -Syu --needed --noconfirm base-devel
        - sed -i '/E_ROOT/d' /usr/bin/makepkg
        - cd inkscape-git
        - makepkg -s --noconfirm
    binaries_artifacts:
        path: "*.pkg.tar.zst"
