container:
    image: archlinux/base
    cpu: 8
    memory: 24G

task:
    script:
        - pacman -Syu --needed --noconfirm sudo base-devel
        - useradd builder
        - passwd -d buildser
        - echo 'builder ALL=(ALL) ALL' > /etc/sudoers.d/00-builder
        - sudo -u builder bash -c 'cd inkscape-git && makepkg -s --noconfirm'
    binaries_artifacts:
        path: "*.pkg.tar.zst"
